from .matching_prompt import MATCHING_SYSTEM_PROMPT, MATCHING_USER_PROMPT
from .mcq_prompt import MCQ_V2_SYSTEM_PROMPT, MCQ_V2_USER_PROMPT
from .capabilities_prompt import CAPABILITIES_SYSTEM_PROMPT, CAPABILITIES_USER_PROMPT
from .code_evaluation_prompt import CODE_EVALUATION_SYSTEM_PROMPT, CODE_EVALUATION_USER_PROMPT
from .match_v2_prompt import MATCH_V2_SYSTEM_PROMPT, MATCH_V2_USER_PROMPT
from .coding_prompt import CODING_ASSIGNMENT_SYSTEM_PROMPT, CODING_ASSIGNMENT_USER_PROMPT

__all__ = [
    "MATCHING_SYSTEM_PROMPT",
    "MATCHING_USER_PROMPT",
    "MCQ_V2_SYSTEM_PROMPT",
    "MCQ_V2_USER_PROMPT",
    "CAPABILITIES_SYSTEM_PROMPT",
    "CAPABILITIES_USER_PROMPT",
    "CODE_EVALUATION_SYSTEM_PROMPT",
    "CODE_EVALUATION_USER_PROMPT",
    "MATCH_V2_SYSTEM_PROMPT",
    "MATCH_V2_USER_PROMPT",
    "CODING_ASSIGNMENT_SYSTEM_PROMPT",
    "CODING_ASSIGNMENT_USER_PROMPT",
]
