from .matching_prompt import MATCHING_SYSTEM_PROMPT, MATCHING_USER_PROMPT
from .mcq_prompt import MCQ_SYSTEM_PROMPT, MCQ_USER_PROMPT
from .capabilities_prompt import CAPABILITIES_SYSTEM_PROMPT, CAPABILITIES_USER_PROMPT
from .code_evaluation_prompt import CODE_EVALUATION_SYSTEM_PROMPT, CODE_EVALUATION_USER_PROMPT

__all__ = [
    "MATCHING_SYSTEM_PROMPT",
    "MATCHING_USER_PROMPT",
    "MCQ_SYSTEM_PROMPT",
    "MCQ_USER_PROMPT",
    "CAPABILITIES_SYSTEM_PROMPT",
    "CAPABILITIES_USER_PROMPT",
    "CODE_EVALUATION_SYSTEM_PROMPT",
    "CODE_EVALUATION_USER_PROMPT",
]
